server:
  port: 8080
spring:
  datasource:

    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 1
#
#  rabbitmq:
#    host: 127.0.0.1
#    username: guest
#    password: guest
#
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300


  #logging.level.root=info
  #logging.path=/spring/log
  #开启驼峰命名匹配规则
 # mybatis.configuration.map-underscore-to-camel-case=true
  #logging.level.com.kn.springbootlearn.mapper=debug
  #debug=false
  mail:
    host: smtp.qq.com
    username: 1123542383@qq.com
    password: tvbyqtpcavfzfhja